apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-qwbrt #must exist
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.125"],"port":30729,"protocol":"TCP","serviceName":"mysql:dev-jialineport","allNodes":true}]'
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-mysql-dev-jialin
  name: dev-jialin
  selfLink: /apis/apps/v1/namespaces/mysql/deployments/dev-jialin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-mysql-dev-jialin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      namespace: default
      annotations:
        # cattle.io/timestamp: "2021-03-10T07:20:49Z"
        field.cattle.io/ports: '[[{"containerPort":22,"dnsName":"dev-jialin-nodeport","hostPort":0,"kind":"NodePort","name":"p22","protocol":"TCP","sourcePort":0}]]'
      # creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-mysql-dev-jialin
    spec:
      containers:
      - image: devzone:1.7.5
        imagePullPolicy: IfNotPresent
        name: dev212-bcmm-1
        ports:
        - containerPort: 22
          name: p22
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /home/dev/devzone
          name: vol-devzone
        - mountPath: /home/dev/go/src
          name: vol-go-src
        - mountPath: /home/dev/go/pkg
          name: vol-go-pkg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/jialin/devzone
          type: DirectoryOrCreate
        name: vol-devzone
      - hostPath:
          path: /home/jialin/qngosrc
          type: DirectoryOrCreate
        name: vol-go-src
      - hostPath:
          path: /home/jialin/qngopkg
          type: DirectoryOrCreate
        name: vol-go-pkg
status: {}
