version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq-server
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - rabbitmq-net

  # Publisher service
  publisher:
    image: alpine-curl:latest
    container_name: rabbitmq-publisher
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: ["sh", "/scripts/publisher.sh"]
    networks:
      - rabbitmq-net
    restart: "no"

  # Subscriber service
  subscriber:
    image: alpine-curl:latest
    container_name: rabbitmq-subscriber
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: ["sh", "/scripts/subscriber.sh"]
    networks:
      - rabbitmq-net
    restart: "no"

volumes:
  rabbitmq_data:

networks:
  rabbitmq-net:
    driver: bridge

